RunDir: "/n/home06/nbalasus/blended_tropomi_gosat_methane"
StorageDir: "/n/holylfs05/LABS/jacob_lab/nbalasus/blended_tropomi_gosat_methane"
Partition: serial_requeue
Cores: 16
CondaEnv: ch4_env 

TimeThreshold: 60
DistanceThreshold: 5
GlobalOffsetGOSAT: 8.9
TimeFLAML: 1800
Model: lgbm
a: 1.26
b: 0.13

Make_Conda_Env: true
Download_GOSAT: true
Download_TROPOMI: true
Download_TCCON: true
Process_GOSAT: true
Process_TROPOMI: true
Pair_TROPOMI_GOSAT: true
Process_TROPOMI_GOSAT_Pairs: true
Pair_GOSAT_TCCON: true
Run_FLAML: true
Predict_Delta_GOSAT_TROPOMI: true
Pair_TROPOMI_TCCON: true
SHAP_Explainer: true
Write_NetCDF: true
Paired_Regrid: true
GOSAT_Regrid: true
TROPOMI_Regrid: true
Oversample_TROPOMI: true
