RunDir: "/n/home06/nbalasus/blended_tropomi_gosat_methane"
StorageDir: "/n/holylfs05/LABS/jacob_lab/nbalasus/blended_tropomi_gosat_methane"
Partition: huce_ice
CondaEnv: ch4_env
Debug: true

GlobalOffsetGOSAT: 9.2
TimeFLAML: 3600
Model: lgbm
a: 1.18
b: -0.40

Make_Conda_Env: true
Download_GOSAT: true
Download_TROPOMI: true
Download_TCCON: true
Calculate_Delta_GOSAT_TCCON: true
Calculate_Delta_TROPOMI_GOSAT: true
Run_FLAML_SHAP: true
Write_Blended_Files: true
Calculate_Delta_TROPOMI_TCCON: true
Oversample_TROPOMI: true