name: blnd_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib=3.7.1
  - numpy=1.23.5
  - jupyterlab=3.6.1
  - ipykernel=6.19.2
  - notebook=6.5.2
  - jupyter=1.0.0
  - netcdf4=1.6.3
  - pandas=1.5.3
  - cartopy=0.21.1
  - pyproj=3.4.1
  - scipy=1.10.0
  - shap=0.41.0
  - geopy=2.3.0
  - geopandas=0.12.2
  - flaml=1.1.3
  - pyyaml=6.0
  - scikit-learn=1.2.0