name: ch4_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib=3.5.2
  - numpy=1.21.5
  - jupyterlab=3.4.0
  - ipykernel=6.15.2
  - notebook=6.5.2
  - jupyter=1.0.0
  - netcdf4=1.5.8
  - pandas=1.4.2
  - cartopy=0.20.2
  - pyproj=3.3.1
  - scipy=1.7.3
  - shap=0.41.0
  - geopy=2.2.0
  - geopandas=0.10.2
  - flaml=1.0.14
  - pyyaml=6.0
  - pip=22.2.2
  - pip:
    - cmcrameri==1.4